### ISSUE TITLE
Broken link on GitHub about section

### ISSUE THREAD

**Issue by yangroro** [schollz/find3#208] opened 2021-03-13 07:43 UTC
![Screen Shot 2021-03-13 at 16 40 34](https://user-images.githubusercontent.com/4294015/111023169-d7d4dd80-841a-11eb-8197-b7c135e83d16.png)
Link on GitHub about section shows [www.internalpositioning.com/doc](https://www.internalpositioning.com/doc).   But they return 404 HTTP Not Found error because of trailing slash
The link [www.internalpositioning.com/doc](https://www.internalpositioning.com/doc) not works. It should be [www.internalpositioning.com/doc/](https://www.internalpositioning.com/doc/) or fix web server configs.

**Comment by MMK21Hub** [comment] 2022-06-20 18:01
Duplicate of #185

**Closed as not planned** 2022-08-04 05:22 UTC
