### ISSUE TITLE
Timeframes

### ISSUE THREAD

**Issue by JapSeyz** [schollz/find3#16] opened 2018-03-07 11:55 UTC
Being able to select a timeframe, or go back in time to see all devices at a certain point in time would be a very useful feature for creating statistics after an ended event, if the server is used for that.

**Comment by victorhooi** [comment] 2018-03-07 23:11
I think this is related to storing historical location data (e.g. InfluxDB):

https://github.com/schollz/find3/issues/13

**Comment by victorhooi** [comment] 2018-03-10 09:54
I think this can be closed as a dupe of #13 (and we can add details/comments there).

**Closed** 2018-03-10 10:01 UTC
