### ISSUE TITLE
broken link in repo about tab

### ISSUE THREAD

**Issue by rtpHarry** [schollz/find3#213] opened 2021-04-27 09:21 UTC
It's just missing a `/` on the end:

https://www.internalpositioning.com/doc/

Without it you get a 404:

https://www.internalpositioning.com/doc

![image](https://user-images.githubusercontent.com/1038062/116218308-4f986680-a742-11eb-9a16-70e28fd171a1.png)

**Comment by MMK21Hub** [comment] 2022-06-20 18:01
Duplicate of #185

**Closed as completed** 2022-06-22 13:37 UTC
